---
name: Deploy Server Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via Ansible Pull
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute Ansible Pull on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            # Wait for dpkg lock to be released (handles unattended-upgrade conflicts)
            wait_for_lock() {
              echo "Waiting for dpkg lock to be released..."
              while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || \
                    sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1 || \
                    sudo fuser /var/cache/apt/archives/lock >/dev/null 2>&1; do
                echo "Lock is held, waiting 5 seconds..."
                sleep 5
              done
              echo "Lock released, proceeding..."
            }

            # Install Ansible if not present
            if ! command -v ansible-pull &> /dev/null; then
              echo "Installing Ansible..."
              wait_for_lock
              sudo apt-get update
              wait_for_lock
              sudo apt-get install -y software-properties-common
              wait_for_lock
              sudo apt-add-repository --yes --update ppa:ansible/ansible
              wait_for_lock
              sudo apt-get install -y ansible
            fi

            # Run ansible-pull
            sudo ansible-pull \
              -U https://github.com/${{ github.repository }}.git \
              -C ${{ github.sha }} \
              -i localhost, \
              ansible/playbook.yml
