---
name: Deploy Server Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'ansible/**'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via Ansible Pull
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute Ansible Pull on Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script_stop: true
          script: |
            # Install Ansible if not present
            if ! command -v ansible-pull &> /dev/null; then
              echo "Installing Ansible..."
              sudo apt-get update
              sudo apt-get install -y software-properties-common
              sudo apt-add-repository --yes --update ppa:ansible/ansible
              sudo apt-get install -y ansible
            fi

            # Run ansible-pull
            sudo ansible-pull \
              -U https://github.com/${{ github.repository }}.git \
              -C ${{ github.sha }} \
              -i localhost, \
              ansible/playbook.yml
